---
- name: Fetch playbooks from GitHub repo and create Job Templates (Red Hat supported version)
  hosts: localhost
  gather_facts: no
  collections:
    - redhat_cop.controller_configuration

  vars:
    github_api_url: "https://api.github.com/repos/san985tos/SOE-2025/contents/templates"
    controller_host: "https://your-aap-controller"
    controller_username: "admin"
    controller_password: "your-password"
    validate_certs: false

    project_name: demo
    inventory_name: Demo Inventory
    credential_name: aws
    job_type: run

  tasks:
    - name: Get contents of templates directory from GitHub
      uri:
        url: "{{ github_api_url }}"
        method: GET
        return_content: yes
        headers:
          Accept: application/vnd.github.v3+json
      register: github_response

    - name: Extract .yml playbooks from GitHub response
      set_fact:
        playbooks: >-
          {{ github_response.json | selectattr('name', 'search', '\\.yml$')
                                   | map(attribute='name')
                                   | map('regex_replace', '^(.*)$', 'templates/\\1')
                                   | list }}

    - name: Create job templates using redhat_cop.controller_configuration
      job_template:
        name: "{{ item | basename | regex_replace('\\.yml$', '') }}"
        project: "{{ project_name }}"
        inventory: "{{ inventory_name }}"
        credential: "{{ credential_name }}"
        playbook: "{{ item }}"
        job_type: "{{ job_type }}"
        become_enabled: true
        ask_variables_on_launch: true
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ validate_certs }}"
      loop: "{{ playbooks }}"
      delegate_to: localhost
