---
- name: Dynamically create job templates for playbooks in Git project
  hosts: localhost
  gather_facts: false
  vars:
    controller_host: url
    controller_username: username
    controller_password: password
    validate_certs: false

    project_name: demo
    inventory_name: Demo Inventory
    credential_name: aws
    job_type: run

    github_api_url: "https://api.github.com/repos/san985tos/SOE-2025/contents/templates"

  tasks:
    - name: Get list of playbooks from GitHub templates directory
      uri:
        url: "{{ github_api_url }}"
        method: GET
        return_content: yes
        headers:
          Accept: application/vnd.github.v3+json
      register: github_response

    - name: Extract playbook file names
      set_fact:
        playbooks: >-
          {{ github_response.json
             | selectattr('name', 'regex_search', '\\.ya?ml$')
             | map(attribute='name')
             | map('regex_replace', '^(.*)$', 'templates/\\1')
             | list }}

    - name: Show parsed playbook list
      debug:
        var: playbooks

    - name: Create job templates for each playbook
      ansible.controller.job_template:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ validate_certs }}"

        name: "{{ item | basename | regex_replace('\\.ya?ml$', '') }}"
        project: "{{ project_name }}"
        playbook: "{{ item }}"
        inventory: "{{ inventory_name }}"
        credential: "{{ credential_name }}"
        job_type: "{{ job_type }}"
        become_enabled: true
        ask_variables_on_launch: true
        state: present
      loop: "{{ playbooks }}"
