---
- name: Create job templates for predefined playbooks
  hosts: localhost
  gather_facts: false
  vars:

    controller_host: https://your-controller-url
    controller_username: admin
    controller_password: your-password
    validate_certs: false

    project_name: demo
    inventory_name: Demo Inventory
    credential_name: aws
    job_type: run

    playbooks:
      - templates/1-VPCsetup.yaml
      - templates/2-createRHELs.yaml
      - templates/satellite-VM-Deployment.yaml
      - templates/satellite-APP-Deployment.yaml

  tasks:
    - name: Show parsed playbook list
      debug:
        var: playbooks

    - name: Create job templates for each playbook
      ansible.controller.job_template:
        name: "{{ item | basename | regex_replace('\\.ya?ml$', '') }}"
        project: "{{ project_name }}"
        playbook: "{{ item }}"
        inventory: "{{ inventory_name }}"
        credential: "{{ credential_name }}"
        job_type: "{{ job_type }}"
        become_enabled: false
        ask_variables_on_launch: false
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: "{{ validate_certs }}"
        state: present
      loop: "{{ playbooks }}"
