---
- name: Create RHEL 9 EC2 instances with unique names
  hosts: localhost
  gather_facts: no
  vars:
    aws_region: us-east-2
    vpc_name: demo
    aws_instance_type: t2.micro
    aws_instance_ami_id: ami-0a482bdfdf4a33e61
    aws_key_pair_name: demo  
    number_of_instances: 1

  tasks:
    - name: Get VPC info by Name tag
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: vpc_info

    - name: Get subnet info by VPC ID
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].id }}"
      register: subnet_info

    - name: Show first Subnet ID found
      debug:
        msg: "Subnet ID is {{ subnet_info.subnets[0].id }}"

    - name: Provision EC2 instances with unique names
      amazon.aws.ec2_instance:
        instance_type: "{{ aws_instance_type }}"
        key_name: "{{ aws_key_pair_name }}"
        image_id: "{{ aws_instance_ami_id }}"
        region: "{{ aws_region }}"
        security_group: "ansible_tower_sg"
        wait: yes
        network:
          assign_public_ip: yes
        vpc_subnet_id: "{{ subnet_info.subnets[0].id }}"
        tags:
          Name: "RHEL9-{{ 99999 | random }}-{{ i }}"
          Type: RHEL
      loop: "{{ range(0, number_of_instances | int) | list }}"
      loop_control:
        loop_var: i
        label: "Creating RHEL instance #{{ i + 1 }}"

    - name: Inspect ec2_result content
      debug:
        var: ec2_result