---
- name: Delete rh-amazon-rhui-client
  hosts: all
  become: yes

  tasks:
    - name: Remove RHUI packages using shell
      shell: |
        yum remove -y rh-amazon-rhui-client* rhui-aws-rhel9 rh-amazon-rhui-config rhui-client-config-server-9

    - name: Clean subscription manager
      shell: subscription-manager clean

    - name: Enable repo management in subscription-manager config
      shell: subscription-manager config --rhsm.manage_repos=1