---
- name: Setup Red Hat Satellite 6.17 on RHEL 9
  hosts: all
  become: yes
  vars:
    rhsm_username: username
    rhsm_password: password

  tasks:
    - name: Remove RHUI packages
      yum:
        name:
          - rh-amazon-rhui-client*
          - rhui-aws-rhel9
          - rh-amazon-rhui-config
          - rhui-client-config-server-9
        state: absent
        autoremove: yes

    - name: Clean subscription manager
      command: subscription-manager clean

    - name: Register to Red Hat
      command: >
        subscription-manager register
        --username={{ rhsm_username }}
        --password={{ rhsm_password }}
        --force
      register: register_output

    - name: Enable repo management in subscription-manager config
      command: subscription-manager config --rhsm.manage_repos=1

    - name: Disable all repositories
      command: subscription-manager repos --disable "*"

    - name: Enable required repos
      command: >
        subscription-manager repos
        --enable=rhel-9-for-x86_64-baseos-rpms
        --enable=rhel-9-for-x86_64-appstream-rpms
        --enable=satellite-6.17-for-rhel-9-x86_64-rpms
        --enable=satellite-maintenance-6.17-for-rhel-9-x86_64-rpms

    - name: Install fapolicyd
      dnf:
        name: fapolicyd
        state: present

    - name: Enable and start fapolicyd
      systemd:
        name: fapolicyd
        enabled: yes
        state: started

    - name: Upgrade system packages
      dnf:
        name: '*'
        state: latest
        update_only: yes

    - name: Install satellite package
      dnf:
        name: satellite
        state: present

    - name: Run satellite-installer
      command: >
        satellite-installer --scenario satellite
        --foreman-initial-organization "Default"
        --foreman-initial-location "Default"
        --foreman-initial-admin-username admin
        --foreman-initial-admin-password r3dh4t1!
      args:
        creates: /etc/foreman-installer/scenarios.d/satellite-answers.yaml

    - name: Install insights-client
      command: satellite-maintain packages install insights-client

    - name: Register with Insights
      command: satellite-installer --register-with-insights
