---
- name: Create RHEL 9 EC2 instance.
  hosts: localhost
  gather_facts: no
  vars:
    aws_region: us-east-2
    vpc_name: SOEdemo
    aws_instance_type: m5.2xlarge
    aws_instance_ami_id: ami-023c6ad2a87d58f18
    aws_instance_name: "Satellite-6.17"
    aws_key_pair_name: demo  
    number_of_instances: 1


  tasks:
    - name: Get VPC info by Name tag
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: vpc_info

    - name: Get subnet info by VPC ID
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].id }}"
      register: subnet_info

    - name: Show first Subnet ID found
      debug:
        msg: "Subnet ID is {{ subnet_info.subnets[0].id }}"

    - name: Provision EC2 instances
      amazon.aws.ec2_instance:
        instance_type: "{{ aws_instance_type }}"
        key_name: "{{ aws_key_pair_name }}"
        image_id: "{{ aws_instance_ami_id }}"
        region: "{{ aws_region }}"
        count: "{{ number_of_instances }}"
        security_group: "SOEdemo_sg"
        wait: yes
        network:
          assign_public_ip: yes   
        vpc_subnet_id: "{{ subnet_info.subnets[0].id }}"
        tags:
          Name: "{{ aws_instance_name }}"
          Type: "Satellite-6.17"
        volumes:
          - device_name: /dev/xvda
            ebs:
              volume_size: 100
              volume_type: gp3
              delete_on_termination: true
          - device_name: /dev/sdb
            ebs:
              volume_size: 300
              volume_type: gp3
              iops: 12000
              delete_on_termination: true
      register: ec2_result

    - name: Inspect ec2_result content
      debug:
        var: ec2_result